# Generated by Django 5.0.7 on 2024-07-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_image',
            field=models.ImageField(upload_to='tweet'),
        ),
    ]
