# Generated by Django 5.0.7 on 2024-07-23 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_tweet_tweet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_image',
            field=models.ImageField(upload_to='tweets/'),
        ),
    ]
